#!/bin/bash

# First build the shared library for the exchanger.
g++ -I ../CyclicBarrier/ -c -g -std=c++17 -fPIC Exchanger.cpp
g++ -I ../CyclicBarrier/ -g -std=c++17 -fPIC -shared Exchanger.o -o libExchanger.so

# Now build the Examples.

linkerFlags="-L ../CyclicBarrier -lpthread -lCyclicBarrier -lPocoFoundation -L. -lExchanger"

for fileItem in $(ls Example*.cpp)
do
	g++ -I ../CyclicBarrier/ -g -std=c++17 $fileItem -o ${fileItem%.cpp}.out $linkerFlags
done

# Remove object files at the end. 
rm -f *.o
